#!/bin/bash
# Bash script that archives selected Free Dale Askey web sites using the WARC ISO format.
HOME=/home/nruest/Dropbox/mellen-askey/arxiv/sites
DATE=`date +"%Y_%m_%d"`
SITES=/home/nruest/git/arxivdaleascii/arxivdaleascii-sites.txt
index=0
pad=`printf "%03d"`

cd $HOME
mkdir FDA_$DATE
cd FDA_$DATE

cat $SITES | while read line; do
  let "index++"
  echo $pad$index
  echo Attempting to archive: $line
  echo ...
  mkdir $DATE_$pad$index
  cd $DATE_$pad$index
  /usr/local/bin/wget --mirror --convert-links --no-parent --random-wait --page-requisites --warc-file=$DATE_$pad$index "$line"
  cd $HOME/FDA_$DATE
  zip -r $DATE_$pad$index.zip $DATE_$pad$index
  rm -rf $DATE_$pad$index
  echo "$(date) - $line archived" >> /var/log/daleascii.log
done
