#!/bin/bash
# Bash script that archives selected Free Dale Askey web sites using the WARC ISO format.
HOME=/home/nruest/Dropbox/mellen-askey/arxiv/sites
DATE=`date +"%Y_%m_%d"`
SITES=/home/nruest/git/arxivdaleascii/arxivdaleascii-sites.txt
index=0
pad=`printf "%03d"`

cd $HOME
mkdir FDA_$DATE
cd FDA_$DATE

cat $SITES | while read line; do
  let "index++"
  mkdir $DATE_$pad$index
  cd $DATE_$pad$index
  xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter "$line" $pad$index.pdf
  xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver "$line" temp.png
  pngcrush temp.png $pad$index.png
  rm temp.png
  /usr/local/bin/wget --mirror --convert-links --no-parent --random-wait --page-requisites --warc-file=$DATE_$pad$index "$line"
  cd $HOME/FDA_$DATE
  zip -r $DATE_$pad$index.zip $DATE_$pad$index
  rm -rf $DATE_$pad$index
  echo "$(date) - $line archived" >> /var/log/daleascii.log
done
